### PR TITLE
change Option to Optional in javadsl

### LINKED ISSUE #37: optionalSession in the javadsl should use java.util.Optional, not scala.Option

### PR DESCRIPTION
**Pull request by mihbor**
closes #37

### CODE REVIEW

**Comment by kijanowski** [comment]
Thank you! 👍

**Comment by mihbor** [comment]
I'm not familiar with versioning in sbt projects but, if it's at all similar to maven, shouldn't the version now be the next snapshot?

**Comment by kijanowski** [comment]
yes and I'll prepare a release during the next day :)

**Comment by mihbor** [comment]
Awesome, thanks!

**Pull request merged**
