### PR TITLE
Upgrade to Akka 2.4.9 and sbt 0.13.12

### PR DESCRIPTION
**Pull request by hseeberger**

### CODE REVIEW

**Comment by adamw** [comment]
Thanks! Though as it's a minor Akka release, I think it is binary compatible with previous releases, so a new release of akka-http-session is not necesary?

**Comment by hseeberger** [comment]
Not sure. Akka HTTP is still experimental in 2.4.9, hence there might be binary incompatibilities.

**Comment by adamw** [comment]
Released 0.2.7 built agains akka 2.4.9 :)

**Comment by hseeberger** [comment]
Thanks, mate!

**Pull request merged**
